project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Expérimentation des IA pour l'utilisation de logiciels statistiques"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - text: "Accueil"
        href: index.qmd
      - section: "Bien démarrer en R"
        contents:
          - href: 1_demarrer/R_starter.qmd
            text: "Bien commencer avec R et Rstudio"
          - href: 1_demarrer/R_prerequis.qmd
            text: "Que faut-il installer pour coder en R ?"
          - href: 1_demarrer/R_comment_coder.qmd
            text: "Comment coder en R"
          - href: 1_demarrer/R_documentation_R.qmd
            text: "Documentation pour débuter en R"
      - section: "Importer des données"
        contents:
          - href: 2_import_donnees/R_import_donnees.qmd
            text: "Importer des données sous R"
          - href: 2_import_donnees/R_import_csv.qmd
            text: "Importer un fichier CSV"
          - href: 2_import_donnees/R_import_sas.qmd
            text: "Importer un fichier SAS"
          - href: 2_import_donnees/R_import_parquet.qmd
            text: "Importer un fichier Parquet"
          - href: 2_import_donnees/R_import_xls.qmd
            text: "Importer un fichier XLS"
          - href: 2_import_donnees/R_import_ods.qmd
            text: "Importer un fichier ODS"
          - href: 2_import_donnees/R_librairie_import.qmd
            text: "Quelles librairies et fonctions utiliser ?"
          - href: 2_import_donnees/R_import_donnees_volumineuses.qmd
            text: "Importer des données volumineuses sous R"
      - section: "Nettoyage et préparation des données"
        contents:
          - href: 3_prep_donnees/R_operations_apres_import.qmd
            text: "Que faire après avoir importer des données"
          - href: 3_prep_donnees/R_detecter_donnees_manquantes.qmd
            text: "Détecter les données manquantes"
          - href: 3_prep_donnees/R_traitement_donnees_manquantes
            text: "Traiter les données manquantes"
          - href: 3_prep_donnees/R_creer_variable.qmd
            text: "Créer de nouvelles variables"
          - href: 3_prep_donnees/R_creer_filtre.qmd
            text: "Appliquer un filtre"
          - href: 3_prep_donnees/R_recoder_variable.qmd
            text: "Recoder une variable"
          - href: 3_prep_donnees/R_detecter_valeurs_aberrantes.qmd
            text: "Détecter les valeurs aberrantes"
          - href: 3_prep_donnees/R_renommer_variable.qmd
            text: "Renommer une variable"
          - href: 3_prep_donnees/R_joint.qmd
            text: "Joindre deux tables"
      - section: "Analyse des données"
        contents:
          - href: 4_analyse_donnees/R_analyser_donnees.qmd
            text: "Analyser ses données"
          - href: 4_analyse_donnees/R_compter.qmd
            text: "Compter ses données"
          - href: 4_analyse_donnees/R_analyser_var_quali.qmd
            text: "Analyser une variable qualitative"
          - href: 4_analyse_donnees/R_analyser_var_quanti.qmd
            text: "Analyser une variable quantitative"
          - href: 4_analyse_donnees/R_stats_desc.qmd
            text: "Obtenir les statistiques descriptives d'une variable"
          - href: 4_analyse_donnees/R_nom_variables.qmd
            text: "Obtenir tous les noms de variables"
          - href: 4_analyse_donnees/R_appliquer_ponderation.qmd
            text: "Appliquer des pondérations"
          - href: 4_analyse_donnees/R_caract.qmd
            text: "Rechercher une chaîne de caractères"
          - href: 4_analyse_donnees/R_quartiles.qmd
            text: "Calculer les quartiles d'une variable"
      - section: "Redressement des données"
        contents:
          - href: 5_redressement_donnees/R_redresser_variable_manquante.qmd
            text: "Redresser une variable manquante"
          - href: 5_redressement_donnees/R_reponderer.qmd
            text: "Repondérer"
          - href: 5_redressement_donnees/R_corriger_non_reponse.qmd
            text: "Correction de la non réponse"
          - href: 5_redressement_donnees/R_corriger_non_reponse_totale.qmd
            text: "Corriger la non réponse totale"
          - href: 5_redressement_donnees/R_corriger_non_reponse_partielle.qmd
            text: "Corriger la non réponse partielle"
      - section: "Analyses inférentielles"
        contents:
          - href: 6_analyse_inferentielle/R_reg_log.qmd
            text: "Régression logistique en R"
      - section: "Interprétation des résultats"
        contents:
          - href: R_staR_templaterter.qmd
            text: ""
      - section: "Rédaction du rapport"
        contents:
          - href: R_template.qmd
            text: ""
      - section: "Diffusion des résultats"
        contents:
          - href: 7_diffusion/R_avancee_openxlsx.qmd
            text: "Exporter des statistiques avec openxlsx"
      - section: "Évaluation et réflexion"
        contents:
          - href: R_template.qmd
            text: ""
      - section: "Usage avancé"
        contents:
          - href: Z_usage_avance/R_avancee_partie_entiere.qmd
            text: "Partie entière en R"
          - href: R_template.qmd
            text: "Template de fiche"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true