project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Expérimentation des IA pour l'utilisation de logiciels statistiques"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - text: "Accueil"
        href: index.qmd
      - section: "Bien démarrer en R"
        contents:
          - href: 1_demarrer/R_starter.qmd
            text: "Bien commencer avec R et Rstudio"
      - section: "Importer des données"
        contents:
          - href: 2_import_donnees/R_import_donnees.qmd
            text: "Importer des données sous R"
      - section: "Nettoyage et préparation des données"
        contents:
          - href: R_template.qmd
            text: ""
	  - href: 3_nettoyage_donnees/R_joint.qmd
            text: ""
      - section: "Analyse des données"
        contents:
          - href: R_template.qmd
            text: ""
      - section: "Analyses inférentielles"
        contents:
          - href: 4_analyse_inferentielle/R_reg_log.qmd
            text: "Régression logistique en R"
      - section: "Interprétation des résultats"
        contents:
          - href: R_staR_templaterter.qmd
            text: ""
      - section: "Rédaction du rapport"
        contents:
          - href: R_template.qmd
            text: ""
      - section: "Diffusion des résultats"
        contents:
          - href: 7_diffusion/R_avancee_openxlsx.qmd
            text: "Exporter des statistiques avec openxlsx"
      - section: "Évaluation et réflexion"
        contents:
          - href: R_template.qmd
            text: ""
      - section: "Usage avancé"
        contents:
          - href: Z_usage_avance/R_avancee_partie_entiere.qmd
            text: "Partie entière en R"
          - href: R_template.qmd
            text: "Template de fiche"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true