project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Expérimentation des IA pour l'utilisation de logiciels statistiques"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - text: "Accueil"
        href: index.qmd
      - section: "Usage classique en statistique"
        contents:
          - href: R_starter.qmd
            text: "Bien commencer avec R et Rstudio"
      - section: "Usage avancé"
        contents:
          - href: R_avancee_openxlsx.qmd
            text: "Exporter des statistiques avec openxlsx"
          - href: R_avancee_partie_entiere.qmd
            text: "Partie entière en R"
          - href: R_reg_log.qmd
            text: "Régression logistique en R"
          - href: R_template.qmd
            text: "Template de fiche"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true